apiVersion: v1
kind: Namespace
metadata:
  name: quota-example
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: resource-quota
  namespace: quota-example
spec:
  hard:
    limits.cpu: 2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: example
  namespace: quota-example
spec:
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            cpu: 500m
